#bottoken にbotのトークンを入れてください
bottoken: 'testtoken'
#channelidにチャンネルのIDを入れてください
channelid: 000
#lunachatモードを機能させるか否か true/false
lunachat: true
#翻訳を可能にするか
translate: true
#translate true ならマイクロソフト翻訳apitokenを
translation_api_key: 'apikey'
#個別のサーバjoin&quitメッセージ on/off
joinquitmsg: 'on'
#muteされているリスト
mutes:
#cmuteされているリスト
commmandmutes:
#muteする時間(分)
mutedtime: 30
#muteする判定のライン(%)
#例:80なら すべてのチャットが80%以上一致している場合mute
mutedpercent: 80
